title: Laksayo's portfolio and blog
author: laksayo
email: laksayo.feedtheshark@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Showcase of art and blog

# Header Links
homepage: https://laksayo.github.com
instagram_username: laksayo
github_username:  laksayo




# Build settings
theme: jekyll-theme-portfolio

plugins:
 - jekyll-feed
 - jekyll-seo-tag
